services:

  pedidos:
    build: ./pedidos
    ports:
      - "5000:5000"

  inventario:
    build: ./inventario
    ports:
      - "5001:5001"

  pagos:
    build: ./pagos
    ports:
      - "5002:5002"

  monitor:
    build: ./monitor
    ports:
      - "5003:5003"